office_admin/clients/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.profile, name='profile'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', views.logout_page, name='logout'),
    url(r'^order/$', include("orders.urls", namespace='orders'))
]

office_admin/office_admin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include("clients.urls", namespace='clients')),
    url(r'^admin/', admin.site.urls),
    url(r'^order/', include("orders.urls", namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

office_admin/orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.order_page, name='create_order'),
]

office_admin/clients/models.py
from django.db import models
from django.contrib.auth.models import User

class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    area = models.CharField(max_length=100)
    
    def __unicode__(self):
        return self.user.username

office_admin/orders/models.py
from django.db import models
from clients.models import Client
from django.utils import timezone

class Order(models.Model):
    STATUS_CHOICES = (
                        ('pending', 'Pending'),
                        ('accepted', 'Accepted'),
                        ('rejected', 'Rejected'),
                        ('completed', 'Completed'),
                     )
    user = models.ForeignKey(Client)
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(  max_length=25,
                                choices = STATUS_CHOICES,
                                default='pending',
                            )

    def __unicode__(self):
        return self.name

class Transaction(models.Model):
    order = models.ForeignKey(Order)
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    price = models.FloatField()
    payment = models.FloatField()
    comments = models.TextField(max_length=500)

office_admin/clients/forms.py
import re

from django import forms
from django.core.exceptions import ObjectDoesNotExist

from django.contrib.auth.models import User

class RegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(
                    label='Password',
                    widget=forms.PasswordInput())
    password2 = forms.CharField(
                    label='Password (Again)',
                    widget=forms.PasswordInput())
                    
    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2
            raise forms.ValidationError('Passwords do not match.')
        
    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('Username is already taken.')

office_admin/orders/forms.py
from django import forms
from .models import Order

#from django import newforms as forms
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'category']

office_admin/clients/views.py
from django.shortcuts import redirect, render_to_response
from .forms import RegistrationForm
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.contrib.auth import logout

from django.contrib.auth.models import User

def login(request):
    return render_to_response('login.html')

def logout_page(request):
    logout(request)
    return redirect('clients:login')

def profile(request):
    if request.user.is_authenticated():
        if request.user.is_superuser:
            return HttpResponseRedirect('/admin')
        else:
            user = User.objects.get(username=request.user.username)
    else:
        user = None
    return render_to_response(
                              'profile.html',
                              { 'user': user }
                              )

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                    username=form.cleaned_data['username'],
                    password=form.cleaned_data['password1'],
                    email=form.cleaned_data['email'])
            user.save()
            return redirect('clients:profile')
    else:
        form = RegistrationForm()

    variables = RequestContext(request, {
                            'form': form})
    
    print 'render to response'
    return render_to_response(
                'registration/register.html', variables)

office_admin/orders/views.py
#from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response

from .forms import OrderForm
from .models import Order

def order_page(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = Order.objects.create(
                                         user = request.user,
                                         name = form.cleaned_data['name'],
                                         category = form.cleaned_data['category'],
                                         order_date = timezone.now(),
                                         status = 'Pending'
                                         )
            order.save()
            return HttpResponseRedirect('/order/success/')
    else:
        form = OrderForm()
        
    variables = RequestContext(request, {
                            'form': form})
                         
    return render_to_response(
                'order.html', variables)

office_admin/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>My Office Admin |
        {% block title %}{% endblock %}</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    </head>
    <body>
        <div id="nav" class='col-sm-9 col-sm-offset-3'>
            <a href="{% url "clients:profile" %}">home</a> |
            {% if user.is_authenticated %}
                Welcome {{ user.username }}
                (<a href="{% url "clients:logout" %}">logout</a>)
            {% else %}
                <a href="{% url "clients:login" %}">login</a> |
                <a href="{% url "clients:register" %}">register</a>
            {% endif %}
        </div>
        <div class="col-md-6">
        <h1>{% block head %}{% endblock %}</h1>
        </div>
        <div class="container">
        {% block content %}{% endblock %}
        </div>
    </body>
</html>

office_admin/templates/order.html
{% extends "base.html" %}
{% load url from future %}
{% block title %}Ordering{% endblock %}
{% block head %}Create Order{% endblock %}
{% block content %}
<form method="post" action=".">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="order" />
</form>
{% endblock %}

office_admin/templates/profile.html
{% extends "base.html" %}
{% block title %}User Profile{% endblock %}
{% block head %}User Profile{% endblock %}
{% block content %}
<div class="col-sm-6 col-sm-offset-1">
	{% if user.is_authenticated %}
		<h1> Username: {{ user.username }}</h1>
	{% else %}	
    <p>Welcome!
        You need to <a href="{% url "clients:login" %}">login</a>
        before you can view and edit orders.</p>
    {% endif %}
</div>
{% endblock %}